# Generated by Django 3.1.12 on 2025-02-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at']},
        ),
    ]
