# Generated by Django 3.1.12 on 2025-02-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
