# Generated by Django 3.1.12 on 2025-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fnmae',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ph',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
