# Generated by Django 4.0.10 on 2025-02-27 04:01

from django.db import migrations, models
import musify.models


class Migration(migrations.Migration):

    dependencies = [
        ('musify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(upload_to=musify.models.cover_upload_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(upload_to=musify.models.song_upload_path),
        ),
    ]
