# Generated by Django 4.0.10 on 2025-02-28 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musify', '0002_user_profile_image_alter_music_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='musify.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='musify.user')),
            ],
            options={
                'db_table': 'playlist',
                'ordering': ['-created_at'],
            },
        ),
    ]
